python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS1
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS2
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS3
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS4
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS5
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS6
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS7
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS8
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS9
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS10
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS11
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS12
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS13
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS14
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS15
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS16
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS17
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS18
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS19
python main.py -model Naive -model_path /globalwork/liu/video_track/Naive-baseline/model_20.pth -smoothen -decimal -data_name mupots -feat_path /globalwork/liu/mupots_feat -partition TS20
