python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 0
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 1
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 2
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 3
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 4
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 5
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 6
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 7
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 8
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 9
python main.py -test_only -model Diff -suffix easy_off -save_path /globalwork/liu/track_camera_pose -criterion SmoothL1 -data_name mpihp -data_root /globalwork/data/mpi_inf_3dhp -occ_span 10
